name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  typos-check:
#    name: Spell Check with Typos
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Actions Repository
#        uses: actions/checkout@v4
#      - name: Check spelling with custom config file
#        uses: crate-ci/typos@v1.16.10
#        with:
#          config: ./typos.toml
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --no-frozen-lockfile

      - name: Run eslint
        run: pnpm lint
